image: rocker/tidyverse:latest

pipelines:
  default:
    - step:
        script:
          - cd /opt/atlassian/pipelines/agent/build
          - mkdir -p check/test-results
          - Rscript -e 'devtools::install_deps(".", dependencies=TRUE, upgrade=FALSE)'
          - Rscript -e 'devtools::build()'
          - Rscript -e 'devtools::install(upgrade_dependencies = FALSE)'
          - Rscript -e 'devtools::check(check_dir = "/opt/atlassian/pipelines/agent/build/")'
