definintions:
  steps:
    - step: &build-test
        name: Build and test package
        script:
          - cd $BITBUCKET_CLONE_DIR
          - mkdir -p check/test-results
          - Rscript -e 'devtools::install_deps(".", dependencies=TRUE, upgrade=FALSE)'
          - Rscript -e 'devtools::build()'
          - Rscript -e 'devtools::install(upgrade_dependencies = FALSE)'
          - Rscript -e 'devtools::check(check_dir = "$BITBUCKET_CLONE_DIR")'

image: rocker/tidyverse:latest

pipelines:
  default:
    - step: *build-test
